default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: tucazorron
  password: StantBackend@2023
  host: localhost

development:
  <<: *default
  database: dev_stant

test:
  <<: *default
  database: test_stant

production:
  <<: *default
  database: prod_stant
